name: leaper-lead-status-transition

services:


# ============================================================================================================================================================
# SEND MESSAGES
# ============================================================================================================================================================
  send-messages:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    restart: always
    networks:
      - leaper-network
    volumes:
      - ../../db:/app/db
      - ../../logging:/app/logging
      - ../../api:/app/api
      - ../../messaging:/app/messaging
      - ../../infra:/app/infra
      - ../../utils:/app/utils
      - ../../scheduling:/app/scheduling
      - /var/run/docker.sock:/var/run/docker.sock


# ============================================================================================================================================================
# REDES
# ============================================================================================================================================================
networks:
  leaper-network:
    external: true
