services:


# ============================================================================================================================================================
# WEBHOOK SERVICE
# ============================================================================================================================================================
  webhook_service:
    build:
      context: ./webhook
      dockerfile: Dockerfile
    env_file:
      - ../../.env
      - ../.env
    restart: always
    networks:
      - network_leaper_dev
    volumes:
      - ../../shared:/app/shared
      - ../shared:/app/shared_ai
      - /var/run/docker.sock:/var/run/docker.sock


# ============================================================================================================================================================
# REDES
# ============================================================================================================================================================
networks:
  network_leaper_dev:
    external: true
